//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagmenPortal.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int task_id { get; set; }
        public string parent_id { get; set; }
        public string project_ID { get; set; }
        public string TaskName { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> priority { get; set; }
        public string Status { get; set; }
    }
}
