//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagmenPortal.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string FirstName { get; set; }
        public string Lastname { get; set; }
        public string Employee_ID { get; set; }
        public string project_ID { get; set; }
        public string Task_ID { get; set; }
    }
}
